#############################################################################
# Makefile for building: RoverGauge
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Feb 26 20:40:13 2012
# Project:  RoverGauge.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile RoverGauge.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DROVERGAUGE_VER_MAJOR=0 -DROVERGAUGE_VER_MINOR=1 -DROVERGAUGE_VER_PATCH=0 -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iqledindicator -Ianalogwidgets -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lcomm14cux -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		optionsdialog.cpp \
		faultcodedialog.cpp \
		serialdevenumerator.cpp \
		cuxinterface.cpp \
		aboutbox.cpp \
		qledindicator/qledindicator.cpp \
		analogwidgets/manometer.cpp \
		analogwidgets/led.cpp \
		analogwidgets/abstractmeter.cpp \
		analogwidgets/widgetwithbackground.cpp \
		analogwidgets/functions.cpp moc_mainwindow.cpp \
		moc_cuxinterface.cpp \
		moc_aboutbox.cpp \
		moc_qledindicator.cpp \
		moc_manometer.cpp \
		moc_led.cpp \
		moc_abstractmeter.cpp \
		moc_widgetwithbackground.cpp \
		qrc_rovergauge_resources.cpp
OBJECTS       = main.o \
		mainwindow.o \
		optionsdialog.o \
		faultcodedialog.o \
		serialdevenumerator.o \
		cuxinterface.o \
		aboutbox.o \
		qledindicator.o \
		manometer.o \
		led.o \
		abstractmeter.o \
		widgetwithbackground.o \
		functions.o \
		moc_mainwindow.o \
		moc_cuxinterface.o \
		moc_aboutbox.o \
		moc_qledindicator.o \
		moc_manometer.o \
		moc_led.o \
		moc_abstractmeter.o \
		moc_widgetwithbackground.o \
		qrc_rovergauge_resources.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qledindicator/qledindicator.pri \
		analogwidgets/analogwidgets.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RoverGauge.pro
QMAKE_TARGET  = RoverGauge
DESTDIR       = 
TARGET        = RoverGauge

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RoverGauge.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qledindicator/qledindicator.pri \
		analogwidgets/analogwidgets.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile RoverGauge.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
qledindicator/qledindicator.pri:
analogwidgets/analogwidgets.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile RoverGauge.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RoverGauge1.0.0 || $(MKDIR) .tmp/RoverGauge1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RoverGauge1.0.0/ && $(COPY_FILE) --parents mainwindow.h optionsdialog.h faultcodedialog.h serialdevenumerator.h cuxinterface.h aboutbox.h qledindicator/qledindicator.h analogwidgets/manometer.h analogwidgets/led.h analogwidgets/abstractmeter.h analogwidgets/widgetwithbackground.h analogwidgets/functions.h .tmp/RoverGauge1.0.0/ && $(COPY_FILE) --parents rovergauge_resources.qrc .tmp/RoverGauge1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp optionsdialog.cpp faultcodedialog.cpp serialdevenumerator.cpp cuxinterface.cpp aboutbox.cpp qledindicator/qledindicator.cpp analogwidgets/manometer.cpp analogwidgets/led.cpp analogwidgets/abstractmeter.cpp analogwidgets/widgetwithbackground.cpp analogwidgets/functions.cpp .tmp/RoverGauge1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/RoverGauge1.0.0/ && (cd `dirname .tmp/RoverGauge1.0.0` && $(TAR) RoverGauge1.0.0.tar RoverGauge1.0.0 && $(COMPRESS) RoverGauge1.0.0.tar) && $(MOVE) `dirname .tmp/RoverGauge1.0.0`/RoverGauge1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RoverGauge1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cuxinterface.cpp moc_aboutbox.cpp moc_qledindicator.cpp moc_manometer.cpp moc_led.cpp moc_abstractmeter.cpp moc_widgetwithbackground.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cuxinterface.cpp moc_aboutbox.cpp moc_qledindicator.cpp moc_manometer.cpp moc_led.cpp moc_abstractmeter.cpp moc_widgetwithbackground.cpp
moc_mainwindow.cpp: analogwidgets/manometer.h \
		analogwidgets/abstractmeter.h \
		analogwidgets/widgetwithbackground.h \
		qledindicator/qledindicator.h \
		optionsdialog.h \
		cuxinterface.h \
		aboutbox.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_cuxinterface.cpp: cuxinterface.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) cuxinterface.h -o moc_cuxinterface.cpp

moc_aboutbox.cpp: aboutbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutbox.h -o moc_aboutbox.cpp

moc_qledindicator.cpp: qledindicator/qledindicator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qledindicator/qledindicator.h -o moc_qledindicator.cpp

moc_manometer.cpp: analogwidgets/abstractmeter.h \
		analogwidgets/widgetwithbackground.h \
		analogwidgets/manometer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) analogwidgets/manometer.h -o moc_manometer.cpp

moc_led.cpp: analogwidgets/widgetwithbackground.h \
		analogwidgets/led.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) analogwidgets/led.h -o moc_led.cpp

moc_abstractmeter.cpp: analogwidgets/widgetwithbackground.h \
		analogwidgets/abstractmeter.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) analogwidgets/abstractmeter.h -o moc_abstractmeter.cpp

moc_widgetwithbackground.cpp: analogwidgets/widgetwithbackground.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) analogwidgets/widgetwithbackground.h -o moc_widgetwithbackground.cpp

compiler_rcc_make_all: qrc_rovergauge_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_rovergauge_resources.cpp
qrc_rovergauge_resources.cpp: rovergauge_resources.qrc \
		key.png
	/usr/bin/rcc -name rovergauge_resources rovergauge_resources.qrc -o qrc_rovergauge_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		analogwidgets/manometer.h \
		analogwidgets/abstractmeter.h \
		analogwidgets/widgetwithbackground.h \
		qledindicator/qledindicator.h \
		optionsdialog.h \
		cuxinterface.h \
		aboutbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		analogwidgets/manometer.h \
		analogwidgets/abstractmeter.h \
		analogwidgets/widgetwithbackground.h \
		qledindicator/qledindicator.h \
		optionsdialog.h \
		cuxinterface.h \
		aboutbox.h \
		ui_mainwindow.h \
		faultcodedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		serialdevenumerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

faultcodedialog.o: faultcodedialog.cpp faultcodedialog.h \
		qledindicator/qledindicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o faultcodedialog.o faultcodedialog.cpp

serialdevenumerator.o: serialdevenumerator.cpp serialdevenumerator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialdevenumerator.o serialdevenumerator.cpp

cuxinterface.o: cuxinterface.cpp cuxinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cuxinterface.o cuxinterface.cpp

aboutbox.o: aboutbox.cpp aboutbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutbox.o aboutbox.cpp

qledindicator.o: qledindicator/qledindicator.cpp qledindicator/qledindicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qledindicator.o qledindicator/qledindicator.cpp

manometer.o: analogwidgets/manometer.cpp analogwidgets/manometer.h \
		analogwidgets/abstractmeter.h \
		analogwidgets/widgetwithbackground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o manometer.o analogwidgets/manometer.cpp

led.o: analogwidgets/led.cpp analogwidgets/led.h \
		analogwidgets/widgetwithbackground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o led.o analogwidgets/led.cpp

abstractmeter.o: analogwidgets/abstractmeter.cpp analogwidgets/abstractmeter.h \
		analogwidgets/widgetwithbackground.h \
		analogwidgets/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractmeter.o analogwidgets/abstractmeter.cpp

widgetwithbackground.o: analogwidgets/widgetwithbackground.cpp analogwidgets/widgetwithbackground.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widgetwithbackground.o analogwidgets/widgetwithbackground.cpp

functions.o: analogwidgets/functions.cpp analogwidgets/functions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o functions.o analogwidgets/functions.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cuxinterface.o: moc_cuxinterface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cuxinterface.o moc_cuxinterface.cpp

moc_aboutbox.o: moc_aboutbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutbox.o moc_aboutbox.cpp

moc_qledindicator.o: moc_qledindicator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qledindicator.o moc_qledindicator.cpp

moc_manometer.o: moc_manometer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_manometer.o moc_manometer.cpp

moc_led.o: moc_led.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_led.o moc_led.cpp

moc_abstractmeter.o: moc_abstractmeter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_abstractmeter.o moc_abstractmeter.cpp

moc_widgetwithbackground.o: moc_widgetwithbackground.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widgetwithbackground.o moc_widgetwithbackground.cpp

qrc_rovergauge_resources.o: qrc_rovergauge_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rovergauge_resources.o qrc_rovergauge_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

